language: node_js
node_js:
  - 8
dist: trusty # the operating system of choice that we want to run our tests
sudo: false
addons:
  chrome: stable
before-install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - 'sysctl kernel.unprivileged_userns_clone=1'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
services: # the services that our application depends upon
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
notifications:
  email: false
cache: # Everytime the test runs, travis has to install all of the dependencies in our project, that's why we are caching them at the beginning so that we don't have to install them everytime we run tests
  directories:
    - node_modules
    - client/node_modules
install: # Commands to be executed inside the command line of the virtual machine of travis
  - npm install # install depen.
  - npm run build # build both: server and client
before_script: # start up our server and run tests
  - nohup npm run start &
script:
  - npm run test
